dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install --upgrade -e .[test]
script:
- make test
deploy:
  provider: pypi
  user: jcklie
  skip_existing: true
  password:
    secure: XHMq9++SKJec901oUNoVD3dlWwvWZo0QD7EVyPStbmRZsn/YXade8RnOao6uSMoWGf2Jvdmu6ZiG2AeqOUjtkIUBg6WTjaRpFvEnRM8VfF5RiCSuhz6L6jyB33hsviwUXF1jf/iUP1NR0l58LA2SyQ07MPyobwtlaOU2bOahCgoeo919+ozkkmR+DOg7846I/ZX3T0Pcr9gVG0sr32mOKq1zBwsOMbX1TzXJk/TkszdoXSWgyPpPSx0OqVGhmyYi0i9a22YEM6B+dgsKhRDoM7lP2rZURbccxm6BX73NDuiM1ritFXJZFHuuFQq5BQVwFeHI0kj2ZQwN2GrwPvJEur1DqSE/NEQNFOPkYx274w8XODBegk7MhYFDz5oJWUIwzcC4nzp3Hzyg4HZxsEWrOr5HQ8cG51wDJuVB7Kei+ZUtxYp1mrcgZipUGCSb2XL+Eh5FZnx71KjOYiWVHaa6HgGNQPo509tvoeTDBFDJWWIK7ELSLlEUR9ZGipCEU2bUchNN7N9J1p1DVwHEH9K81Irrq5zmQuDKwTWGfYfKA6tyWkQavr4/g6BMCgQcut3OX02vkMsxFkJPlEqNKYO37JZAQ6S0L7tTipUT57X7ZyXxw4z1oDc3SPFtGL09niWot4h/WSLyb9uq3HpWYADembay0fJNxqdZG8v7rCSVnZA=
  on:
    tags: true
